version: '3.9'

services:
  web:
    build: ./frontend/
    depends_on:
      - db
      - backend
    ports:
      - 80:80
    environment:
      - BACKEND_URL=backend:8000

  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=db_user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017

  backend:
    build: ./backend/
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - MONGODB_URL=mongodb://db:27017/mongodb
